// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwQAqUUk-77iW30VV2yYB6MIZqF6JQUfc',
    appId: '1:771585564836:web:0667c33dd7d644e9df8631',
    messagingSenderId: '771585564836',
    projectId: 'nodeapp2-27252',
    authDomain: 'nodeapp2-27252.firebaseapp.com',
    storageBucket: 'nodeapp2-27252.firebasestorage.app',
    measurementId: 'G-TGQ3W0JSCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-kNpTFIOh3hKDR2IqgPorO5TxCJlELhI',
    appId: '1:771585564836:android:c48e1201a06eee59df8631',
    messagingSenderId: '771585564836',
    projectId: 'nodeapp2-27252',
    storageBucket: 'nodeapp2-27252.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs2vTb64slaTz3udjWOLHlzoMkkEd3wwY',
    appId: '1:771585564836:ios:67476fb50842d6fcdf8631',
    messagingSenderId: '771585564836',
    projectId: 'nodeapp2-27252',
    storageBucket: 'nodeapp2-27252.firebasestorage.app',
    androidClientId:
        '771585564836-96m8j3vt7vn6pvh4032ghor95sm8g9et.apps.googleusercontent.com',
    iosBundleId: 'com.example.nodeApp2',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs2vTb64slaTz3udjWOLHlzoMkkEd3wwY',
    appId: '1:771585564836:ios:67476fb50842d6fcdf8631',
    messagingSenderId: '771585564836',
    projectId: 'nodeapp2-27252',
    storageBucket: 'nodeapp2-27252.firebasestorage.app',
    androidClientId:
        '771585564836-96m8j3vt7vn6pvh4032ghor95sm8g9et.apps.googleusercontent.com',
    iosBundleId: 'com.example.nodeApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwQAqUUk-77iW30VV2yYB6MIZqF6JQUfc',
    appId: '1:771585564836:web:9ac698b6d1cd3c08df8631',
    messagingSenderId: '771585564836',
    projectId: 'nodeapp2-27252',
    authDomain: 'nodeapp2-27252.firebaseapp.com',
    storageBucket: 'nodeapp2-27252.firebasestorage.app',
    measurementId: 'G-8MTD9P6HPZ',
  );
}
